---
name: "Foo Action"
description: "Testing"

inputs:
  msg:
    required: true
    description: "Message to print"

outputs: {}

runs:
  using: composite
  steps:
    - name: Echo
      shell: bash
      run: |
        echo "${{ inputs.msg }}"
