on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Debug
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.workflow_ref: ${{ github.workflow_ref }}"

      - name: "Call action"
        uses: lindeskar/gha-test/foo-action@main
        with:
          msg: "Hello world"
