on:
  workflow_call:
    inputs:
      action-version:
        type: string
        required: true

jobs:
  find_tf_dirs:
    runs-on: ubuntu-latest
    outputs:
      tf_dirs: '["foo", "bar"]'
    steps:
      - name: "Debug"
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.workflow_ref: ${{ github.workflow_ref }}"
          echo "inputs.action-version: ${{ inputs.action-version }}"

  terraform:
    runs-on: ubuntu-latest
    needs: find_tf_dirs
    if: ${{ toJson(fromJson(needs.find_tf_dirs.outputs.tf_dirs)) != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        tf_dir: ${{fromJson(needs.find_tf_dirs.outputs.tf_dirs)}}
    steps:
      - name: Debug
        run: |
          echo "tf_dir: ${{ matrix.tf_dir }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.workflow_ref: ${{ github.workflow_ref }}"
          echo "inputs.action-version: ${{ inputs.action-version }}"

      - name: fail one tf_dir
        if: ${{ matrix.tf_dir == 'fail_me' }}
        run: |
          exit 1

      - name: "Call action"
        uses: lindeskar/gha-test/foo-action@${{ inputs.action-version }}
        with:
          arg: ${{ tojson(inputs.action-version) }}
          msg: "Hello world"

  confirm-success:
    name: "Confirm success"
    if: ${{ !cancelled() }}
    needs:
      - find_tf_dirs
      - terraform
    runs-on: ubuntu-latest
    steps:
      - name: Fail if any Terraform job failed
        if: ${{ needs.terraform.result == 'failure' && toJson(fromJson(needs.find_tf_dirs.outputs.tf_dirs)) != '[]' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('At least one Terraform job failed - check the GitHub logs for details')
